site_name: 'ðŸŽ´: `dek`: The decorator-decorator ðŸŽ´'

theme:
  name: material

  palette:
    primary:
      'deepOrange'

  font:
    text:
      Roboto
    code:
      Roboto Mono

extra_css: [extra.css]

plugins:
    - mkdocstrings
